[package]
name = "nostromo-notes"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.29.0", features = ["crossterm"] }
crossterm = "0.27.0"
tui-textarea = "0.7.0"
walkdir = "2.5.0"
dirs = "5.0.1"
fuzzy-matcher = "0.3.7"
